name: Update Latest Branch

on:
  push:
    tags:
      - 'v*'

jobs:
  update-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update latest branch
        run: |
          git checkout -B latest
          git push origin latest --force