name: Update Latest Branch

on:
  push:
    tags:
      - 'v*'

jobs:
  update-latest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to latest branch
        run: |
          git config user.name "esuescun"
          git config user.email "esuescun@curatechsas.com"
          git push https://x-access-token:${{ secrets.WORKFLOW }}@github.com/${{ github.repository }} HEAD:latest